### PR TITLE
Add space before year in incollection

### PR DESCRIPTION
**Pull request by mlhetland**
Just following the pattern for similar drivers.

### CODE REVIEW

**Comment by NorwegianRockCat** [comment]
I don't see anything wrong with this, but could you add an incollection item to the tests? That way we can make sure it is correct for the future too.

**Comment by mlhetland** [comment]
Certainly! I was about to, but I guess I got lazy ;D

**Comment by mlhetland** [comment]
There are some other issues with years that I'm not sure how to address (and issues seem to be disabled for this repo?):
- For a bare-bones `misc` entry, there will be a spurious comma between the title and the year (because of an unconditional `\addcomma`).
- The use of `organization+location+date` in `misc` leads to an additional year at the end. Seems to work fine if replaced by `organization+location`, but I'm not sure if that's how it should be handled.

**Comment by mlhetland** [comment]
Ah, no, `organization+location` doesn't exist, I guess.

**Comment by NorwegianRockCat** [comment]
Hi @mlhetland 

I enabled issues if you want to put the issue there. I believe I just forked the original repo because it wasn't working with newer versions of BibLaTeX. So, I didn't have the expectation that I would start collecting changes. :-)

Anyway, I'll look a bit closer at these later today.

**Comment by mlhetland** [comment]
Indeed!

Well, I'm not sure where these efforts are best directed, but your fork seemed more active/responsive (as is also pointed out by [an issue](https://github.com/latextemplates/LNCS/issues/3) at [latextemplates](https://github.com/latextemplates)), which is why I added some PRs here :-)

**Comment by NorwegianRockCat** [comment]
LGTM. Thank you.

**Pull request merged**
